// Generated by music/make_voiceover.py; do not edit.
export const VO = {"hi": {"durs": [222, 271, 188, 387, 246, 547, 230], "total": 2091}, "en": {"durs": [207, 282, 187, 379, 220, 533, 217], "total": 2025}} as const;
