import React from "react";
import { AbsoluteFill, Audio, Sequence, staticFile } from "remotion";
import { C } from "./common";
import { setContact, setLang } from "./i18n";
import { VO } from "./vo";
import { DripProblems, ManualDrip, SolarPhone, WmEndCard, WmReveal, ZonesRun } from "./scenes/wm";
import { HowItWorks } from "./scenes/HowItWorks";

// WaterMaster explainer with a voice-over per scene. Scene lengths come from vo.ts
// (generated by music/make_voiceover.py from the narration audio).
const STEPS = [
  { title: "ज़ोन प्लान करें", detail: "वाल्व, समय और खाद; रोज़ या हर कुछ दिन" },
  { title: "खेत अपने-आप चले", detail: "वाल्व खुला हो तभी पंप; खाद साथ में" },
  { title: "हिसाब और अलर्ट", detail: "फ्लो, प्रेशर और बिजली का रिकॉर्ड" },
];
const How: React.FC<{ dur: number }> = ({ dur }) => (
  <HowItWorks dur={dur} steps={STEPS} bg={`radial-gradient(circle at 50% 30%, ${C.tealMid}, ${C.teal} 55%, ${C.deep})`} accent={C.leaf} ink={C.ink} />
);
const SCENES = [ManualDrip, DripProblems, WmReveal, ZonesRun, SolarPhone, How, WmEndCard];

export const WmExplainer: React.FC<{ lang: "hi" | "en" }> = ({ lang }) => {
  setLang(lang);
  setContact(lang === "en" ? "Call: +91 70629 41806" : "कॉल करें: +91 70629 41806");
  const durs = VO[lang].durs;
  let from = 0;
  return (
    <AbsoluteFill style={{ background: "#000" }}>
      {SCENES.map((Scene, i) => {
        const start = from;
        from += durs[i];
        return (
          <Sequence key={i} from={start} durationInFrames={durs[i]}>
            <Scene dur={durs[i]} />
            <Sequence from={12}>
              <Audio src={staticFile(`vo/${lang}/s${i}.mp3`)} />
            </Sequence>
          </Sequence>
        );
      })}
      <Audio src={staticFile("wm-music.wav")} loop volume={0.12} />
    </AbsoluteFill>
  );
};
