// Generated by music/make_voiceover.py; do not edit.
export const VO = {"hi": {"durs": [219, 243, 163, 329, 192, 578, 290], "total": 2014}, "en": {"durs": [247, 231, 154, 331, 180, 450, 277], "total": 1870}} as const;
