import React from "react";
import { AbsoluteFill, Audio, Sequence, staticFile } from "remotion";
import { C } from "./common";
import { setContact, setLang } from "./i18n";
import { VO } from "./vo";
import { NightTrip } from "./scenes/NightTrip";
import { Problems } from "./scenes/Problems";
import { Reveal } from "./scenes/Reveal";
import { FarmAuto } from "./scenes/FarmAuto";
import { SleepPhone } from "./scenes/SleepPhone";
import { HowItWorks } from "./scenes/HowItWorks";
import { EndCard } from "./scenes/EndCard";

// Longer explainer with a voice-over per scene. Scene lengths come from vo.ts
// (generated by music/make_voiceover.py from the narration audio).
const STEPS = [
  { title: "मास्टर सम्प पढ़ता है", detail: "3 लेवल तक फ्लोट स्विच" },
  { title: "पंप रेडियो से चालू/बंद", detail: "LoRa से, पंप के मौजूदा स्टार्टर के ज़रिए" },
  { title: "फोन पर सब दिखता है", detail: "हर पंप, बिजली और पानी का फ्लो" },
];
const How: React.FC<{ dur: number }> = ({ dur }) => (
  <HowItWorks dur={dur} steps={STEPS} bg={`radial-gradient(circle at 50% 30%, #245C3E, ${C.green} 55%, ${C.deep})`} accent={C.amber} ink={C.ink} />
);
const SCENES = [NightTrip, Problems, Reveal, FarmAuto, SleepPhone, How, EndCard];

export const WpcExplainer: React.FC<{ lang: "hi" | "en" }> = ({ lang }) => {
  setLang(lang);
  setContact(lang === "en" ? "Call: +91 70629 41806" : "कॉल करें: +91 70629 41806");
  const durs = VO[lang].durs;
  let from = 0;
  return (
    <AbsoluteFill style={{ background: "#000" }}>
      {SCENES.map((Scene, i) => {
        const start = from;
        from += durs[i];
        return (
          <Sequence key={i} from={start} durationInFrames={durs[i]}>
            <Scene dur={durs[i]} />
            <Sequence from={12}>
              <Audio src={staticFile(`vo/${lang}/s${i}.mp3`)} />
            </Sequence>
          </Sequence>
        );
      })}
      <Audio src={staticFile("wpc-music.wav")} loop volume={0.12} />
    </AbsoluteFill>
  );
};
