"""Pre-build: generate src/board_map.h from the kit pin map.

products/ASC-StudentKit/hardware/pinmap.json is the single source of truth for
which GPIO sits behind each port (check_pinmap.py checks it). This writes the
same table as C so the firmware can't drift from the hardware. Also runnable
by hand: `python3 scripts/gen_board_map.py`.
"""
import json
import os

try:
    Import("env")  # noqa: F821 -- provided by PlatformIO's SCons environment
    PROJECT = env["PROJECT_DIR"]  # noqa: F821
except NameError:
    PROJECT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PINMAP = os.path.normpath(os.path.join(PROJECT, "../../hardware/pinmap.json"))
OUT = os.path.join(PROJECT, "src", "board_map.h")

with open(PINMAP) as f:
    pm = json.load(f)


def gpio(board, signal):
    for g, s in board["pins"].items():
        if s == signal:
            return int(g)
    return -1


def board_struct(key):
    b = pm["boards"][key]
    s = [gpio(b, f"S{i}") for i in range(1, 9)]
    o = [gpio(b, f"OUT{i}") for i in range(1, 5)]
    fields = {
        "sensorPorts": b["sensor_ports"], "i2cPorts": b["i2c_ports"], "relays": b["relays"],
        "i2cExtSda": gpio(b, "I2C_EXT_SDA"), "i2cExtScl": gpio(b, "I2C_EXT_SCL"),
        "i2cIntSda": gpio(b, "I2C_INT_SDA"), "i2cIntScl": gpio(b, "I2C_INT_SCL"),
        "led": gpio(b, "LED"), "buzzer": gpio(b, "BUZZER"), "pairBtn": gpio(b, "PAIR_BTN"),
        "rtcInt": gpio(b, "RTC_INT"), "vinSense": gpio(b, "VIN_SENSE"), "vbatAdc": gpio(b, "VBAT_ADC"),
        "vbatEn": gpio(b, "VBAT_EN"), "valve": gpio(b, "VALVE"),
    }
    body = ", ".join(f".{k} = {v}" for k, v in fields.items())
    return (f'  {{ .name = "{key}", .sensor = {{{", ".join(map(str, s))}}}, '
            f'.out = {{{", ".join(map(str, o))}}}, {body} }}')


ids = pm["board_id"]
text = f"""// GENERATED by scripts/gen_board_map.py from hardware/pinmap.json. Do not edit.
#pragma once
#include <stdint.h>

struct BoardMap {{
  const char* name;
  int8_t sensor[8];  // S1..S8, -1 = not on this board
  int8_t out[4];     // OUT1..OUT4
  uint8_t sensorPorts, i2cPorts, relays;
  int8_t i2cExtSda, i2cExtScl, i2cIntSda, i2cIntScl;
  int8_t led, buzzer, pairBtn, rtcInt, vinSense, vbatAdc, vbatEn, valve;
}};

static const BoardMap BOARDS[] = {{
{board_struct("mini")},
{board_struct("mega")},
}};

// BOARD_ID divider ratios (fraction of 3V3) and the pin they are read on.
static const int8_t BOARD_ID_PIN = {gpio(pm["boards"]["mini"], "BOARD_ID")};
static const float BOARD_ID_MINI = {ids["mini"]}f;
static const float BOARD_ID_MEGA = {ids["mega"]}f;
"""

old = open(OUT).read() if os.path.exists(OUT) else ""
if old != text:
    with open(OUT, "w") as f:
        f.write(text)
    print(f"[gen_board_map] wrote {OUT}")
