"""Generate the explainer voice-over: one clip per scene, Hindi and English.

Uses the macOS `say` voices Lekha (hi_IN) and Aman (en_IN) and ffmpeg
(set FFMPEG=/path/to/ffmpeg if it is not on PATH). Writes public/vo/<lang>/s<i>.mp3
and src/vo.ts with each scene's length in frames (narration + padding, never
shorter than the original ad scene).
"""
import json, math, os, re, subprocess, sys, tempfile
from narration import NARRATION, MIN_FRAMES

FPS = 30
FFMPEG = os.environ.get("FFMPEG", "ffmpeg")
VOICES = {"hi": ("Lekha", "170"), "en": ("Aman", "165")}
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def duration(path):
    err = subprocess.run([FFMPEG, "-i", path], capture_output=True, text=True).stderr
    h, m, s = re.search(r"Duration: (\d+):(\d+):([\d.]+)", err).groups()
    return int(h) * 3600 + int(m) * 60 + float(s)

out = {}
for lang, lines in NARRATION.items():
    voice, rate = VOICES[lang]
    d = os.path.join(ROOT, "public", "vo", lang)
    os.makedirs(d, exist_ok=True)
    durs = []
    for i, text in enumerate(lines):
        with tempfile.TemporaryDirectory() as tmp:
            aiff = os.path.join(tmp, "a.aiff")
            subprocess.run(["say", "-v", voice, "-r", rate, "-o", aiff, text], check=True)
            mp3 = os.path.join(d, f"s{i}.mp3")
            subprocess.run([FFMPEG, "-y", "-loglevel", "error", "-i", aiff, "-ac", "1", "-b:a", "96k", mp3], check=True)
        secs = duration(mp3)
        durs.append(max(MIN_FRAMES[i], math.ceil(secs * FPS) + 12 + 24))
    out[lang] = {"durs": durs, "total": sum(durs)}
    print(lang, durs, round(sum(durs) / FPS, 1), "s")

with open(os.path.join(ROOT, "src", "vo.ts"), "w") as f:
    f.write("// Generated by music/make_voiceover.py; do not edit.\n")
    f.write("export const VO = " + json.dumps(out) + " as const;\n")
