[env:ping]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    jgromes/RadioLib @ ^6.6.0
monitor_speed = 115200
upload_speed = 921600
build_flags = -D BOARD_ROLE=0

[env:pong]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    jgromes/RadioLib @ ^6.6.0
monitor_speed = 115200
upload_speed = 921600
build_flags = -D BOARD_ROLE=1

[env:idle]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    jgromes/RadioLib @ ^6.6.0
monitor_speed = 115200
upload_speed = 921600
build_flags = -D BOARD_ROLE=2
