#pragma once

#include <ArduinoJson.h>

#include "THStore.hpp"
#include "baseMQTTMessenger.hpp"

#include "calendarUtils.hpp"

class MQTTMessenger : public BaseMQTTMessenger {
 public:
    /**
     * send TH
     * token and txTopic are relevant only for onDemand responses
     * time, seqNum, live are relevant only for responses generated by timed cycles
     */
    void sendTH(float temp, float humi, Time time, unsigned int seqNum, bool live, String token="", String txTopic="");

    /**
     * send current values of parameter
     */
    void sendParameter(String token, String txTopic);

    /**
     * Send acknowledgement
     * * detailMsg: additional details
     */
    void sendAck(String token, String txTopic, const char* detailMsg=nullptr);

    /**
     * Send negative response for a command
     * * errMsg: mandatory error msg
     */
    void sendError(String token, const char* errMsg, String txTopic);
    void sendError(String token, String errMsg, String txTopic);

    /**
     * Send error
     */
    void sendError(String Error_string);

    /**
     * send a textual event to platform, initiated by the platform
     */
    void sendEvent(const char* description);
    void sendEvent(String description);

  private:
    /* send Payload */
    void sendPayload(String payload); // TODO: String ref
    void sendPayload(String topic, String payload); // TODO: String ref
   
    /* determine mac to be set */
    String txMac();
};

extern MQTTMessenger mqttMessenger; // the singleton instance
