[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
build_flags =
  -DCONFIG_ASYNC_TCP_RUNNING_CORE=1
  -DCORE_DEBUG_LEVEL=0
lib_deps =
  bblanchon/ArduinoJson @ ^7.0.0
  knolleary/PubSubClient @ ^2.8
  https://github.com/ESP32Async/AsyncTCP.git
  https://github.com/ESP32Async/ESPAsyncWebServer.git
