import React from "react";
import { AbsoluteFill, Audio, Sequence, staticFile } from "remotion";
import { C } from "./common";
import { setContact, setLang } from "./i18n";
import { VO } from "./vo";
import { Chore } from "./scenes/Chore";
import { Problems } from "./scenes/Problems";
import { Reveal } from "./scenes/Reveal";
import { Watering } from "./scenes/Watering";
import { PhoneAway } from "./scenes/PhoneAway";
import { HowItWorks } from "./scenes/HowItWorks";
import { EndCard } from "./scenes/EndCard";

// Longer explainer with a voice-over per scene. Scene lengths come from vo.ts
// (generated by music/make_voiceover.py from the narration audio).
const STEPS = [
  { title: "शेड्यूल सेट करें", detail: "दिन में 4 बार तक, लीटर या मिनट से" },
  { title: "समय पर पानी", detail: "इंटरनेट के बिना भी" },
  { title: "फ्लो से पक्का", detail: "हर लीटर गिना जाता है" },
];
const How: React.FC<{ dur: number }> = ({ dur }) => (
  <HowItWorks dur={dur} steps={STEPS} bg={`radial-gradient(circle at 50% 30%, ${C.tealMid}, ${C.teal} 55%, ${C.deep})`} accent={C.leaf} ink={C.ink} />
);
const SCENES = [Chore, Problems, Reveal, Watering, PhoneAway, How, EndCard];

export const Fg1Explainer: React.FC<{ lang: "hi" | "en" }> = ({ lang }) => {
  setLang(lang);
  setContact(lang === "en" ? "Call: +91 70629 41806" : "कॉल करें: +91 70629 41806");
  const durs = VO[lang].durs;
  let from = 0;
  return (
    <AbsoluteFill style={{ background: "#000" }}>
      {SCENES.map((Scene, i) => {
        const start = from;
        from += durs[i];
        return (
          <Sequence key={i} from={start} durationInFrames={durs[i]}>
            <Scene dur={durs[i]} />
            <Sequence from={12}>
              <Audio src={staticFile(`vo/${lang}/s${i}.mp3`)} />
            </Sequence>
          </Sequence>
        );
      })}
      <Audio src={staticFile("fg1-music.wav")} loop volume={0.12} />
    </AbsoluteFill>
  );
};
