// Generated by music/make_voiceover.py; do not edit.
export const VO = {"hi": {"durs": [170, 253, 172, 305, 268, 486, 229], "total": 1883}, "en": {"durs": [178, 246, 171, 295, 290, 439, 212], "total": 1831}} as const;
