[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    jgromes/RadioLib @ ^6.6.0
    bblanchon/ArduinoJson @ ^7.0.0

monitor_speed = 115200
upload_speed = 921600
; adjust to your Master board's port -- may differ from the Pump Node's
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
