; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
;
[platformio]
default_envs = 
	wifi
  ;gsm

[env]
platform = espressif8266
board = d1_mini
framework = arduino
lib_deps = 
  symlink://../baselib
  robtillaart/DHTNEW@^0.4.12

monitor_speed = 115200
monitor_flags = -e

build_type = debug

build_flags =
  -I.
  -DSERIAL_SWAPPED
  -DMONITOR_SPEED=115200
	-DMQTT_MAX_PACKET_SIZE=512
  ;-DMQTT_BROKER=\"mqtt.agrisensorsandcontrols.com\"
  ;-DMQTT_BROKER=\"prodbroker.sasyasystems.com\"
	-DMQTT_BROKER=\"testbroker.sasyasystems.com\"
	;-DOTA_URL=\"http://prodapp.agrisensorsandcontrols.com:8080/FOTA\"
  -DOTA_URL=\"http://fota.sasyasystems.com\"
	-DPLATFORM_STORAGE_MARKER=34
	;-DMQTT_TOPIC_STAGE=2
  -DLED_PIN_BLUE=4 
	-DPRODUCT_TYPE=\"TH\"

[env:gsm]
build_flags = 
	-DUSE_GSM
	-DGSM_APN=\"www\"
	-DTINY_GSM_RX_BUFFER=128
  ;-DDUMP_AT_COMMANDS
  ;-DTINY_GSM_DEBUG=Console
	${env.build_flags}


[env:wifi]
build_flags = 
	${env.build_flags}
	-DFEATURE_WIFI_MANAGER
