; TH Monitor - Group 3: MQTT. Joins your WiFi and publishes readings to a public MQTT broker.
[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/DHT sensor library
  adafruit/Adafruit Unified Sensor
  adafruit/RTClib
  knolleary/PubSubClient
  tzapu/WiFiManager
