import React from "react";
import { AbsoluteFill, Audio, Sequence, staticFile } from "remotion";
import { setContact, setLang } from "./i18n";
import { VO as VO_PADDY } from "./vo_paddy";
import { VO as VO_WMPRO } from "./vo_wmpro";
import { HowItWorks } from "./scenes/HowItWorks";
import {
  AwdTube, BigFarmWalk, MotorBox, PADDY, PaddyWalk, PhoneSms, ProApp, ProNode, ValveGrid, WMPRO,
  makeEndCard, makeProblems, makeReveal,
} from "./scenes/concepts";

// Concept-product explainers with a voice-over per scene. Scene lengths come from
// vo_<name>.ts (generated by music/make_voiceover.py <name>).
type Scene = React.FC<{ dur: number }>;

const PADDY_SCENES: Scene[] = [
  PaddyWalk,
  makeProblems("धान की रोज़ की परेशानी", [
    ["ज़्यादा पानी, ज़्यादा बिजली", "💧"],
    ["रात को पंप चलाने खेत", "🌙"],
    ["पंप सूखा चला, जल गया", "🔥"],
  ]),
  makeReveal(PADDY, "अब फोन बताएगा।", "धान सिंचाई सलाहकार", (f) => <MotorBox x={130} y={120} w={300} f={f} />),
  AwdTube,
  PhoneSms,
  ({ dur }) => (
    <HowItWorks dur={dur} bg={`radial-gradient(circle at 50% 30%, ${PADDY.mid}, ${PADDY.bg} 55%, ${PADDY.deep})`} accent={PADDY.accent} ink={PADDY.accentInk}
      steps={[
        { title: "पाइप में सेंसर", detail: "खेत के पानी का लेवल नापे" },
        { title: "eSIM मोटर कंट्रोलर", detail: "पंप चालू/बंद, ड्राई-रन से बचाव" },
        { title: "सलाह फोन पर", detail: "SMS या कॉल, हिंदी में" },
      ]} />
  ),
  makeEndCard(PADDY, "धान सिंचाई सलाहकार", "धान के खेत के लिए स्मार्ट सिंचाई", ["कम चक्कर, सही पानी", "अनुमानित कीमत ₹5,000 तक", "डीलर और पायलट किसान चाहिए"], (f) => <MotorBox x={20} y={0} w={260} f={f} on />),
];

const WMPRO_SCENES: Scene[] = [
  BigFarmWalk,
  makeProblems("बड़े खेत की परेशानी", [
    ["वाल्व तक तार बिछाना महंगा", "🧵"],
    ["गलत क्रम, असमान पानी", "🔀"],
    ["मज़दूर पर निर्भर", "👷"],
  ]),
  makeReveal(WMPRO, "अब हर वाल्व रेडियो से।", "WM-Pro वायरलेस वाल्व", () => <ProNode x={110} y={140} w={340} a b />),
  ValveGrid,
  ProApp,
  ({ dur }) => (
    <HowItWorks dur={dur} bg={`radial-gradient(circle at 50% 30%, ${WMPRO.mid}, ${WMPRO.bg} 55%, ${WMPRO.deep})`} accent={WMPRO.accent} ink={WMPRO.accentInk}
      steps={[
        { title: "पंप पर मास्टर", detail: "शेड्यूल और पंप कंट्रोल" },
        { title: "हर नोड पर 2 वाल्व", detail: "सोलर/बैटरी, LoRa रेडियो" },
        { title: "क्रम से सिंचाई", detail: "पंप तभी, जब वाल्व खुला" },
      ]} />
  ),
  makeEndCard(WMPRO, "WM-Pro", "वायरलेस वाल्व सिंचाई", ["2 वाल्व वाला नोड लगभग ₹10,000", "5 एकड़ = 5 नोड, 10 वाल्व", "डीलर और पायलट किसान चाहिए"], () => <ProNode x={0} y={20} w={300} a b />),
];

const make = (scenes: Scene[], vo: { hi: { durs: readonly number[] }; en: { durs: readonly number[] } }, name: string) => {
  const Explainer: React.FC<{ lang: "hi" | "en" }> = ({ lang }) => {
    setLang(lang);
    setContact(lang === "en" ? "Call: +91 70629 41806" : "कॉल करें: +91 70629 41806");
    const durs = vo[lang].durs;
    let from = 0;
    return (
      <AbsoluteFill style={{ background: "#000" }}>
        {scenes.map((S, i) => {
          const start = from;
          from += durs[i];
          return (
            <Sequence key={i} from={start} durationInFrames={durs[i]}>
              <S dur={durs[i]} />
              <Sequence from={12}>
                <Audio src={staticFile(`vo/${name}/${lang}/s${i}.mp3`)} />
              </Sequence>
            </Sequence>
          );
        })}
        <Audio src={staticFile("concept-music.wav")} loop volume={0.12} />
      </AbsoluteFill>
    );
  };
  return Explainer;
};

export const PaddyExplainer = make(PADDY_SCENES, VO_PADDY, "paddy");
export const WmProExplainer = make(WMPRO_SCENES, VO_WMPRO, "wmpro");
