// Generated by music/make_voiceover.py; do not edit.
export const VO = {"hi": {"durs": [257, 321, 159, 569, 367, 454, 357], "total": 2484}, "en": {"durs": [250, 280, 159, 540, 347, 387, 356], "total": 2319}} as const;
