// Generated by music/make_voiceover.py; do not edit.
export const VO = {"hi": {"durs": [233, 299, 205, 360, 291, 452, 395], "total": 2235}, "en": {"durs": [241, 294, 201, 360, 254, 393, 380], "total": 2123}} as const;
